45 lines (36 sloc)  1.31 KB
name: ci
on: [push]
env: 
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Uses Flyctl
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      # Creates .env file      
      - name: 'Create env file'
        run: |
          touch .env
          echo DISCORD_TOKEN=${{ secrets.TOKEN }} >> .env
          cat .env
      # Deploys it to fly.io
      - name: 'Deploy to fly.io'
        run: |
          flyctl deploy --no-cache --strategy immediate
